### ISSUE TITLE
Give access to pytorch version

### ISSUE THREAD

**Issue by ruudvlutters** [stes/fan#4]
Hi,

On the front-page of this git repo, you mention a new improved pytorch version at:
github.com/stes/pytorch-fan

This version is not publicly accessible. Can you make it accessible ?, I'm really interested in this normalization method.

Thanks in advance,
Ruud Vlutters

**Comment by stes** [comment]
Hello @ruudvlutters , you can find the public version here: https://github.com/stes/fan-pytorch
The repository there is not quite finished yet. However, feel free to use it as a reference implementation.
